"; Generated by claude, it was to speed up development of the game. Will make my own when i get to level desing eventualy" 

import sys
from PyQt6.QtWidgets import (QApplication, QMainWindow, QWidget, QVBoxLayout, 
                             QHBoxLayout, QGridLayout, QPushButton, QTextEdit, 
                             QLabel, QButtonGroup, QRadioButton, QGroupBox)
from PyQt6.QtCore import Qt
from PyQt6.QtGui import QFont

class LevelEditor(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Sokoban Level Editor")
        self.setGeometry(100, 100, 1000, 700)
        
        # Grid dimensions (40 columns x 30 rows)
        self.cols = 40
        self.rows = 30
        
        # Current selected tile
        self.selected_tile = ' '
        
        # Drawing state for click-drag
        self.is_drawing = False
        
        # Tile definitions
        self.tiles = {
            ' ': ('Empty', '#2b2b2b'),
            'b': ('Wall', '#8b4513'),
            '@': ('Box', '#ffa500'),
            'A': ('Player', '#00ff00'),
            'o': ('Goal', '#ffff00'),
            'B': ('Big Wall', '#654321'),
            '.': ('Floor', '#444444'),
        }
        
        # Grid data
        self.grid_data = [[' ' for _ in range(self.cols)] for _ in range(self.rows)]
        
        # Setup UI
        self.init_ui()
        
    def init_ui(self):
        central_widget = QWidget()
        self.setCentralWidget(central_widget)
        main_layout = QHBoxLayout(central_widget)
        
        # Left side: Grid (fixed size container)
        left_layout = QVBoxLayout()
        
        # Grid container with fixed size
        grid_container = QWidget()
        grid_container.setFixedSize(820, 620)  # Fixed size to prevent resizing
        grid_container.setStyleSheet("background-color: #1e1e1e;")
        
        self.grid_layout = QGridLayout(grid_container)
        self.grid_layout.setSpacing(1)
        self.grid_layout.setContentsMargins(5, 5, 5, 5)
        
        # Create grid buttons
        self.grid_buttons = []
        for row in range(self.rows):
            row_buttons = []
            for col in range(self.cols):
                btn = QPushButton(' ')
                btn.setFixedSize(20, 20)
                btn.setStyleSheet(f"background-color: {self.tiles[' '][1]}; border: 1px solid #000;")
                
                # Mouse events for click-drag
                btn.mousePressEvent = lambda event, r=row, c=col: self.start_drawing(r, c, event)
                btn.mouseReleaseEvent = lambda event: self.stop_drawing(event)
                btn.enterEvent = lambda event, r=row, c=col: self.continue_drawing(r, c, event)
                
                self.grid_layout.addWidget(btn, row, col)
                row_buttons.append(btn)
            self.grid_buttons.append(row_buttons)
        
        left_layout.addWidget(grid_container)
        left_layout.addStretch()  # Push grid to top
        
        # Right side: Controls
        right_layout = QVBoxLayout()
        
        # Tile selector
        selector_group = QGroupBox("Tile Selector")
        selector_layout = QVBoxLayout()
        
        self.tile_buttons = QButtonGroup()
        for i, (char, (name, color)) in enumerate(self.tiles.items()):
            radio = QRadioButton(f"{name} ('{char}')")
            radio.setStyleSheet(f"QRadioButton::indicator:checked {{ background-color: {color}; }}")
            radio.toggled.connect(lambda checked, c=char: self.select_tile(c) if checked else None)
            self.tile_buttons.addButton(radio, i)
            selector_layout.addWidget(radio)
            if char == ' ':
                radio.setChecked(True)
        
        selector_group.setLayout(selector_layout)
        right_layout.addWidget(selector_group)
        
        # Action buttons
        actions_group = QGroupBox("Actions")
        actions_layout = QVBoxLayout()
        
        clear_btn = QPushButton("Clear All")
        clear_btn.clicked.connect(self.clear_grid)
        actions_layout.addWidget(clear_btn)
        
        export_btn = QPushButton("Export to String")
        export_btn.clicked.connect(self.export_to_string)
        actions_layout.addWidget(export_btn)
        
        import_btn = QPushButton("Import from String")
        import_btn.clicked.connect(self.import_from_string)
        actions_layout.addWidget(import_btn)
        
        actions_group.setLayout(actions_layout)
        right_layout.addWidget(actions_group)
        
        # String output area
        string_group = QGroupBox("Level String (1200 chars)")
        string_layout = QVBoxLayout()
        
        self.string_output = QTextEdit()
        self.string_output.setFont(QFont("Courier", 9))
        self.string_output.setPlaceholderText("Level string will appear here...")
        string_layout.addWidget(self.string_output)
        
        string_group.setLayout(string_layout)
        right_layout.addWidget(string_group)
        
        # Add layouts to main
        main_layout.addLayout(left_layout, 3)
        main_layout.addLayout(right_layout, 1)
        
    def select_tile(self, char):
        """Update selected tile"""
        self.selected_tile = char
    
    def start_drawing(self, row, col, event):
        """Start drawing on mouse press"""
        if event.button() == Qt.MouseButton.LeftButton:
            self.is_drawing = True
            self.place_tile(row, col)
    
    def stop_drawing(self, event):
        """Stop drawing on mouse release"""
        if event.button() == Qt.MouseButton.LeftButton:
            self.is_drawing = False
    
    def continue_drawing(self, row, col, event):
        """Continue drawing while dragging"""
        if self.is_drawing:
            self.place_tile(row, col)
        
    def place_tile(self, row, col):
        """Place selected tile on grid"""
        # Update data
        self.grid_data[row][col] = self.selected_tile
        
        # Update button appearance
        btn = self.grid_buttons[row][col]
        btn.setText(self.selected_tile)
        color = self.tiles[self.selected_tile][1]
        btn.setStyleSheet(f"background-color: {color}; border: 1px solid #000; color: white; font-weight: bold;")
        
    def clear_grid(self):
        """Clear entire grid"""
        for row in range(self.rows):
            for col in range(self.cols):
                self.grid_data[row][col] = ' '
                btn = self.grid_buttons[row][col]
                btn.setText(' ')
                btn.setStyleSheet(f"background-color: {self.tiles[' '][1]}; border: 1px solid #000;")
        self.string_output.clear()
        
    def export_to_string(self):
        """Export grid to string format"""
        result = ""
        for row in self.grid_data:
            result += ''.join(row)
        
        self.string_output.setPlainText(result)
        
    def import_from_string(self):
        """Import string to grid"""
        text = self.string_output.toPlainText()
        
        # Validate length
        if len(text) != self.cols * self.rows:
            self.string_output.append(f"\n\nError: Expected {self.cols * self.rows} characters, got {len(text)}")
            return
        
        # Update grid
        for row in range(self.rows):
            for col in range(self.cols):
                idx = row * self.cols + col
                char = text[idx] if idx < len(text) else ' '
                
                # Validate character
                if char not in self.tiles:
                    char = ' '
                
                self.grid_data[row][col] = char
                btn = self.grid_buttons[row][col]
                btn.setText(char)
                color = self.tiles[char][1]
                btn.setStyleSheet(f"background-color: {color}; border: 1px solid #000; color: white; font-weight: bold;")

if __name__ == '__main__':
    app = QApplication(sys.argv)
    app.setStyle('Fusion')  # Modern look
    editor = LevelEditor()
    editor.show()
    sys.exit(app.exec())
